### ISSUE TITLE
Shouldn't undefined be taken into account has a possible result ?

### ISSUE THREAD

**Issue by fmDATA** [bharlow/fm-webdirect-custom#2]
https://github.com/bharlow/fm-webdirect-custom/blob/8c93facf69c64ac5afb344c5d001ebf7b5c79166/html/mysolution19-form/index.html#L155

Here is the doc for satisfies :
https://lancedikson.github.io/bowser/docs/Parser.html#satisfies

I changed the code to (so it works) :
if( platform == false || platform == undefined ) {

**Comment by bharlow** [comment]
Correcting for the next release.
