### ISSUE TITLE
disable /fmi/webd

### ISSUE THREAD

**Issue by ilgio** [bharlow/fm-webdirect-custom#3]
after customized index page with mydomain.com/APP/index.html
How do I disable the address mydomain.com/fmi/webd ?

**Comment by bharlow** [comment]
There have been folks who have used Proxies or iFrames to hide the domain, however you cannot fully disable it as it is part of the product. 

This is something that is beyond the scope of this project as we provide a set of simple HTML pages developers can use as a starting point to make their own.
