### ISSUE TITLE
On mobile dont work

### ISSUE THREAD

**Issue by ilgio** [bharlow/fm-webdirect-custom#4]
on mobile doesn 't work
![IMAGE 2021-07-26 10:53:57](https://user-images.githubusercontent.com/26309528/126962078-ed994184-ecea-40bd-b42e-af32ed9bda1d.jpg)

**Comment by bharlow** [comment]
I updated the text of the minimum browser requirements, there was a mistake in the listed requirements listing for mobile. You can find the specific requirements at: [Requirements for accessing FileMaker WebDirect solutions](https://support.claris.com/s/article/Requirements-for-accessing-FileMaker-WebDirect-solutions-1503693035709?language=en_US)
